baseURL = "https://terryhahm.github.io/"
languageCode = "en-us"
title = "Youngseok Hahm"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Youngseok Hahm"
    description = "Personal blog theme powered by Hugo"
    githubUsername = "terryhahm"
    accent = "blue"
    showBorder = true
    backgroundColor = "white"
    font = "Courgette" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:terryhahm@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/terryhahm/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/youngseok-hahm-79904583/"
    name = "linkedin"
    weight = 3
